name: Build and Deploy
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: "hecrj/setup-rust-action@v1"
        with:
          rust-version: stable
      - name: Install the web target
        run: "rustup target add wasm32-unknown-unknown"
      - name: Install Linux dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libudev-dev zlib1g-dev alsa libasound2-dev
      - name: Add cargo web
        run: cargo install cargo-web
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: cargo web deploy --release
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{ secrets.AUTH_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/deploy
